version: '3.8'

services:
  postgres:
    image: postgres:13.1-alpine3.13
    build:
        context: build/postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
       - ./var/lib/postgres:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    restart: on-failure
    networks:
        - symfony

    php:
      build:
        context: ./build/php
        dockerfile: Dockerfile
      image: sf-docker/php-dev
    ports:
        - 9001:9000
    volumes:
        - "./htdocs:/var/www/html"
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - symfony

    nginx:
      image: nginx:alpine
      ports:
          - 8000:80
      volumes:
        - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        - "./htdocs:/var/www/html"
      depends_on:
        - php
      networks:
        - symfony

    networks:
      symfony:
        name: symfony-driver