version: '3.8'

services:
  postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
       - ./var/lib/postgres:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    restart: on-failure
    networks:
      - symfony

  php:
    build:
      context: ./build/php
      dockerfile: Dockerfile
      args:
        uid: 1000
        gid: 1000
    environment:
      APP_ENV: dev 
      APP_DEBUG: 1
    ports:
      - 9001:9000
    volumes:
      - "./htdocs:/var/www/symfony_docker"
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - symfony

  nginx:
    image: nginx:stable-alpine
    ports:
      - 8080:80
    volumes:
      - ./htdocs:/var/www/symfony_docker
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - symfony

networks:
  symfony:
    name: symfony-driver