version: '3.3'

networks:
  laravel:

services:
  lara-mysql:
    image: mysql:5.7
    container_name: lara-mysql
    restart: unless-stopped
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - laravel

  php:
    build:
      context: build/php
      args:
        uid: ${UID}
        gid: ${GID}
    container_name: lara-php
    volumes:
      - "./htdocs:/var/www/html"
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    ports:
      - "9000:80"
    networks:
      - laravel
