version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8082:80
    volumes:
      - ./htdocs:/var/www/html/wp
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - wp

  php:
    build:
      context: ./build/php
      dockerfile: Dockerfile
      args:
        uid: ${UID}
        gid: ${GID}
    environment:
      APP_ENV: dev 
      APP_DEBUG: 1
    ports:
      - 9001:9000
    volumes:
      - ./htdocs:/var/www/html/wp
    restart: on-failure
    networks:
      - wp

  maria-db:
    image: mariadb:10.6.12
    container_name: maria-db
    ports:
      - 5306:3306
    environment:
      MARIADB_DB: database
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
    volumes: 
      - ./mysql:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - wp

networks:
  wp:
    name: wp-driver